/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;


/**
 *
 * @author tadeo
 */
public class Interfaz extends javax.swing.JFrame {
    //Estas listas son para guardar los datos en respectivos espacios
    ArrayList <String> nom=new ArrayList<>(Collections.nCopies(20," "));
    String nombre[] = new String[20];
    String cuatri[] = new String[20];
    String parcial1[] = new String[20];
    String parcial2[] = new String[20];
    String parcial3[] = new String[20];
    int menu=0,p1=0,p2=0,p3=0;
    
    
    

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        initStyles();
        if (lblIndicador.getText().equals("Menu")){
            lblGuardados.setText(String.valueOf(menu));
        }
    }

    public void initStyles() {
        Titulo.putClientProperty("FlatLaf.style", "font: $h2.font");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        txtCuatri = new javax.swing.JTextField();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        txtCali1 = new javax.swing.JTextField();
        txtCali3 = new javax.swing.JTextField();
        txtCali2 = new javax.swing.JTextField();
        lblIndicador = new javax.swing.JLabel();
        btnDerech = new javax.swing.JButton();
        btnIzquier = new javax.swing.JButton();
        btnDatos = new javax.swing.JButton();
        lblGuardados = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 136, 198));
        jPanel1.setForeground(new java.awt.Color(173, 73, 225));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Calificaciones");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 130, -1));

        label1.setForeground(new java.awt.Color(0, 0, 0));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Ingrese su nombre: ");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 180, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 180, -1));

        label2.setForeground(new java.awt.Color(0, 0, 0));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("Ingrese su cuatrimestre:");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 180, -1));

        txtCuatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuatriActionPerformed(evt);
            }
        });
        jPanel1.add(txtCuatri, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 180, -1));

        label3.setForeground(new java.awt.Color(0, 0, 0));
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, 20));

        label4.setForeground(new java.awt.Color(0, 0, 0));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 180, 20));

        label5.setForeground(new java.awt.Color(0, 0, 0));
        label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 100, 20));

        txtCali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCali1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 150, -1));

        txtCali3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCali3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCali3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 180, -1));

        txtCali2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCali2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCali2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 180, -1));

        lblIndicador.setForeground(new java.awt.Color(0, 0, 0));
        lblIndicador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndicador.setText("Menu");
        jPanel1.add(lblIndicador, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 70, 30));

        btnDerech.setText(">");
        btnDerech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechActionPerformed(evt);
            }
        });
        jPanel1.add(btnDerech, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 40, 30));

        btnIzquier.setText("<");
        btnIzquier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierActionPerformed(evt);
            }
        });
        jPanel1.add(btnIzquier, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 40, 30));

        btnDatos.setText("Guardar Datos");
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });
        jPanel1.add(btnDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 120, -1));

        lblGuardados.setForeground(new java.awt.Color(0, 0, 0));
        lblGuardados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuardados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblGuardados, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 40, 20));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Guardados:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
        // Este boton guardara los datos en las listas
        if (lblIndicador.getText().equals("Menu")) {

            if (menu<=10){
                nombre[menu]=(txtNombre.getText());
                cuatri[menu]=txtCuatri.getText();
                menu=menu+1;
                lblGuardados.setText(String.valueOf(menu));
            }

        }

        if(lblIndicador.getText().equals("Parcial 1")){
            try{
                if (p1<10){
                    float cali1=Integer.valueOf(txtNombre.getText());
                    float cali2=Integer.valueOf(txtCuatri.getText());
                    float cali3=Integer.valueOf(txtCali2.getText());

                    float prom=(cali1+cali2+cali3)/3;
                    parcial1[p1]=String.valueOf(prom);
                    p1=p1+1;
                    lblGuardados.setText(String.valueOf(p1));
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Tuvo un error del tipo: "+e.getMessage());
            }
        }

        if(lblIndicador.getText().equals("Parcial 2")){
            try{
                if (p2<=10){
                    float cali1=Integer.valueOf(txtNombre.getText());
                    float cali2=Integer.valueOf(txtCuatri.getText());
                    float cali3=Integer.valueOf(txtCali2.getText());

                    float prom=(cali1+cali2+cali3)/3;
                    parcial2[p2]=String.valueOf(prom);
                    p2=p2+1;
                    lblGuardados.setText(String.valueOf(p2));
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Tuvo un error del tipo: "+e.getMessage());
            }
        }

        if(lblIndicador.getText().equals("Parcial 3")){
            try{
                if (p3<=10){
                    float cali1=Integer.valueOf(txtNombre.getText());
                    float cali2=Integer.valueOf(txtCuatri.getText());
                    float cali3=Integer.valueOf(txtCali2.getText());

                    float prom=(cali1+cali2+cali3)/3;
                    parcial3[p3]=String.valueOf(prom);
                    p3=p3+1;
                    lblGuardados.setText(String.valueOf(p3));
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Tuvo un error del tipo: "+e.getMessage());
            }
        }

    }//GEN-LAST:event_btnDatosActionPerformed

    private void btnIzquierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierActionPerformed
        // Boton que ejecuta las acciones de ir a la izquierda

        //Este primer if es para regresar el parcial 1 al Menu
        if (lblIndicador.getText().equals("Parcial 1")) {
            Titulo.setText("Calificaciones");
            lblIndicador.setText("Menu");
            label1.setText("Ingrese su nombre: ");
            label2.setText("Ingrese su cuatrimestre: ");
            label3.setText("");
            label4.setText("");
            label5.setText("");
            lblGuardados.setText(String.valueOf(menu));
        } //Este else if es para regresar del parcial 2 al parcial 1
        else if (lblIndicador.getText().equals("Parcial 2")) {
            Titulo.setText("Parcial 1");
            lblIndicador.setText("Parcial 1");
            label1.setText("Ingrese su primer calificación: ");
            txtNombre.setText("");
            label2.setText("Ingrese su segunda calificación: ");
            txtCuatri.setText("");
            label4.setText("Ingrese su tercera calificación: ");
            txtCali2.setText("");
            label4.setForeground(Color.black);
            label3.setText("");
            label5.setText("");
            lblGuardados.setText(String.valueOf(p1));
        } //Este else if es para regresar del parcial 3 al 2
        else if (lblIndicador.getText().equals("Parcial 3")) {
            Titulo.setText("Parcial 2");
            lblIndicador.setText("Parcial 2");
            label1.setText("Ingrese su primer calificación: ");
            txtNombre.setText("");
            label2.setText("Ingrese su segunda calificación: ");
            txtCuatri.setText("");
            label4.setText("Ingrese su tercera calificación: ");
            txtCali2.setText("");
            label4.setForeground(Color.black);
            label3.setText("");
            label5.setText("");
            lblGuardados.setText(String.valueOf(p2));

        } else if (lblIndicador.getText().equals("0")) {
            Titulo.setText("Parcial 3");
            lblIndicador.setText("Parcial 3");
            label1.setText("Ingrese su primer calificación: ");
            txtNombre.setText("");
            label2.setText("Ingrese su segunda calificación: ");
            txtCuatri.setText("");
            label4.setText("Ingrese su tercera calificación: ");
            txtCali2.setText("");
            label4.setForeground(Color.black);
            txtCali1.setText("");
            label3.setText("  ");
            label5.setText("");
            txtCali3.setText("");
            lblGuardados.setText(String.valueOf(p3));
            //El siguiente codigo agrega label esto para poder actualizar si es necesario
        } else {
            try {
                int numero = Integer.valueOf(lblIndicador.getText());
                if (numero == 0) {
                    numero = numero - 1;
                    Titulo.setText("Usuario ");
                    lblIndicador.setText(String.valueOf(numero));
                    label1.setText("Su nombre es: ");
                    txtNombre.setText(nombre[numero]);
                    label2.setText("Su cuatrimestre es: ");
                    txtCuatri.setText(cuatri[numero]);
                    label3.setText("Primer parcial: ");
                    txtCali1.setText(parcial1[numero]);
                    label4.setText("Segundo parcial: ");
                    txtCali2.setText(parcial2[numero]);
                    label5.setText("Tercer parcial: ");
                    txtCali3.setText(parcial3[numero]);

                }
            } catch (Exception e) {

            }

        } try{
            int numero =Integer.valueOf(lblIndicador.getText());
            if (numero>0){
                numero =numero-1;
                Titulo.setText("Usuario ");
                lblIndicador.setText(String.valueOf(numero));
                label1.setText("Su nombre es: ");
                txtNombre.setText(nombre[numero]);
                label2.setText("Su cuatrimestre es: ");
                txtCuatri.setText(cuatri[numero]);
                label3.setText("Primer parcial: ");
                txtCali1.setText(parcial1[numero]);
                label4.setText("Segundo parcial: ");
                txtCali2.setText(parcial2[numero]);
                label5.setText("Tercer parcial: ");
                txtCali3.setText(parcial3[numero]);
            }

        }catch(Exception e){

        }

    }//GEN-LAST:event_btnIzquierActionPerformed

    private void btnDerechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechActionPerformed
        // Este boton ejecuta las acciones de ir a la derecha
        //este if es para cambiar del espacio Menu al espacio Parcial 1
        if (lblIndicador.getText().equals("Menu")) {
            Titulo.setText("Parcial 1");
            lblIndicador.setText("Parcial 1");
            label1.setText("Ingrese su primer calificación: ");
            txtNombre.setText("");
            label2.setText("Ingrese su segunda calificación: ");
            txtCuatri.setText("");
            label4.setText("Ingrese su tercera calificación: ");
            txtCali2.setText("");
            label4.setForeground(Color.black);
            label3.setText("");
            label5.setText("");
            lblGuardados.setText(String.valueOf(p1));

        } //Este else if es para cambiar de espacio del parcial 1 al parcial 2
        else if (lblIndicador.getText().equals("Parcial 1")) {
            Titulo.setText("Parcial 2");
            lblIndicador.setText("Parcial 2");
            label1.setText("Ingrese su primer calificación: ");
            txtNombre.setText("");
            label2.setText("Ingrese su segunda calificación: ");
            txtCuatri.setText("");
            label4.setText("Ingrese su tercera calificación: ");
            txtCali2.setText("");
            label4.setForeground(Color.black);
            label3.setText("");
            label5.setText("");
            lblGuardados.setText(String.valueOf(p2));
        } //El siguiente else if es para cambiar del espacio Parcial 2 al Parcial 3
        else if (lblIndicador.getText().equals("Parcial 2")) {
            Titulo.setText("Parcial 3");
            lblIndicador.setText("Parcial 3");
            label1.setText("Ingrese su primer calificación: ");
            txtNombre.setText("");
            label2.setText("Ingrese su segunda calificación: ");
            txtCuatri.setText("");
            label4.setText("Ingrese su tercera calificación: ");
            txtCali2.setText("");
            label4.setForeground(Color.black);
            label3.setText("");
            label5.setText("");
            lblGuardados.setText(String.valueOf(p3));
        } //Ahora este else if empezara a mostrar los usuarios desde el espacio 0 en adelante
        else if (lblIndicador.getText().equals("Parcial 3")) {
            Titulo.setText("Usuario ");
            lblIndicador.setText("0");
            label1.setText("Su nombre es: ");
            txtNombre.setText(nombre[0]);
            label2.setText("Su cuatrimestre es: ");
            txtCuatri.setText(cuatri[0]);
            label3.setText("Primer parcial: ");
            txtCali1.setText(parcial1[0]);
            label4.setText("Segundo parcial: ");
            txtCali2.setText(parcial2[0]);
            label5.setText("Tercer parcial: ");
            txtCali3.setText(parcial3[0]);

        } else {
            //Este if es para que cuando este en el espacio 0 pueda avanzar en 1 correspondientemente mostrara los valores de esos espacios
            try {
                int numero = Integer.valueOf(lblIndicador.getText());
                if (numero < 10) {
                    numero = numero + 1;

                    Titulo.setText("Usuario ");
                    lblIndicador.setText(String.valueOf(numero));
                    label1.setText("Su nombre es: ");
                    txtNombre.setText(nombre[numero]);
                    label2.setText("Su cuatrimestre es: ");
                    txtCuatri.setText(cuatri[numero]);
                    label3.setText("Primer parcial: ");
                    txtCali1.setText(parcial1[numero]);
                    label4.setText("Segundo parcial: ");
                    txtCali2.setText(parcial2[numero]);
                    label5.setText("Tercer parcial: ");
                    txtCali3.setText(parcial3[numero]);

                }
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_btnDerechActionPerformed

    private void txtCali2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCali2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCali2ActionPerformed

    private void txtCali3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCali3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCali3ActionPerformed

    private void txtCali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCali1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCali1ActionPerformed

    private void txtCuatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuatriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuatriActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            FlatDarkLaf.setup();
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnDatos;
    private javax.swing.JButton btnDerech;
    private javax.swing.JButton btnIzquier;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel lblGuardados;
    private javax.swing.JLabel lblIndicador;
    private javax.swing.JTextField txtCali1;
    private javax.swing.JTextField txtCali2;
    private javax.swing.JTextField txtCali3;
    private javax.swing.JTextField txtCuatri;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
